spring.application.name=lostFoundApplication
server.port=9595

# ===============================
# DATABASE CONFIGURATION (MySQL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/lostfounddb
spring.datasource.username=springuser
spring.datasource.password=Spring@123

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
